Cherry-pick for patch/pull - Add a framework definition, mono-4.5-api
Log message from original changeset:
Add a framework definition, mono-4.5-api

The following error may occur when building NAnt with the mono-4.5
target framework specification, under Mono 6.9.0:

~~~~
[build.ext nant]
/usr/local/src/mono_devo_wk/nant_devsrc/src/NAnt.DotNet/NAnt.DotNet.build
build
            Buildfile:
            file:///usr/local/src/mono_devo_wk/nant_devsrc/src/NAnt.DotNet/NAnt.DotNet.build
            Target framework: Mono 4.5 Profile
            Target(s) specified: build

            build:

            [build csc] Compiling 3 files to
            '/usr/local/src/mono_devo_wk/nant_devsrc/build/mono-4.5.unix/nant-debug/bin/NAnt.exe'.
            [build csc] Compiling 70 files to
            '/usr/local/src/mono_devo_wk/nant_devsrc/build/mono-4.5.unix/nant-debug/bin/NAnt.Core.Tests.dll'.
            [build csc] Compiling 35 files to
            '/usr/local/src/mono_devo_wk/nant_devsrc/build/mono-4.5.unix/nant-debug/bin/NAnt.DotNetTasks.dll'.
                           [resgen] Read in 77 resources from
                           '/usr/local/src/mono_devo_wk/nant_devsrc/src/NAnt.DotNet/Resources/Strings.resx'
                           [resgen] Writing resource file...  Done.
            [build csc]
            /usr/local/src/mono_devo_wk/nant_devsrc/src/NAnt.Console/ConsoleStub.cs(480,17):
            error CS0433: The imported type `System.Xml.XmlNode' is
            defined multiple times
            [build csc] /usr/pkg/lib/mono/4.5/System.Xml.dll (Location
            of the symbol related to previous error)
            [build csc]
            /usr/pkg/lib/mono/4.5-api/System.Xml.dll (Location of the
            symbol related to previous error)
            [build csc]
            /usr/local/src/mono_devo_wk/nant_devsrc/src/NAnt.Console/ConsoleStub.cs(488,17):
            error CS0433: The imported type `System.Xml.XmlElement' is
            defined multiple times
            [build csc] /usr/pkg/lib/mono/4.5/System.Xml.dll (Location
            of the symbol related to previous error)
            [build csc]
            /usr/pkg/lib/mono/4.5-api/System.Xml.dll (Location of the
            symbol related to previous error)
            [build csc]
            /usr/local/src/mono_devo_wk/nant_devsrc/src/NAnt.Console/ConsoleStub.cs(504,17):
            error CS0433: The imported type `System.Xml.XmlNodeList' is
            defined multiple times
            [build csc] /usr/pkg/lib/mono/4.5/System.Xml.dll (Location
            of the symbol related to previous error)
            [build csc]
            /usr/pkg/lib/mono/4.5-api/System.Xml.dll (Location of the
            symbol related to previous error)
            [build csc] Compilation failed: 3 error(s), 0 warnings

            BUILD FAILED - 0 non-fatal error(s), 9 warning(s)

            /usr/local/src/mono_devo_wk/nant_devsrc/src/NAnt.Console/NAnt.Console.build(15,10):
            External Program Failed:
            /usr/pkg/lib/mono/4.5/mcs.exe (return code was 1)
~~~~

In order to limit the usage of System.Xml.dll to the object installed
under /usr/pkg/lib/mono/4.5-api/ this changet uses the path 4.5-api
under the NAnt 'reference-assemblies' and 'tool-paths' configuration
directives, within the NAnt framework definition for 4.5-api

This changeset also updates the main Makefile for the additional
framework symbol, mono-4.5-api and sets this as the default TARGET
specification. Moreover, the default MCS is set to 'mcs' in this
changeset.

This changeset reuses the NAnt.build specification for mono-4.5

This changeset has been tested under a build using Mono 6.9.0 x86-64
locally compiled under pkgsrc, on FreeBSD 11.2.

(cherry picked from commit b2af7314384688aa52fe7d86349f4e2debfce862)